# Site Information
name: gnailuy.com
markdown: redcarpet
highlighter: pygments
permalink: pretty
encoding: utf-8
baseurl: /

# Author Information
author: Yuliang Jin
authorMsg: Data Platform Engineer@Umeng
authorEmail: jinyuliang@umeng.com
authorNickname: gnailuy

# Frequently Used URL
url: http://gnailuy.com
urlAbout: /about

# Navigation Bar Items
navItems:
    - name: home
      url: /
    - name: archive
      url: /archive
    - name: about
      url: /about

# Image Tag
image:
    source: assets/images/_fullsize
    output: images
    presets:
        # Proportional preset
        fullWidth:
            width: 630
