# Site Information
name: gnailuy.com
markdown: redcarpet
pygments: true
permalink: pretty

# Author Information
author: Yuliang Jin
authorMsg: Data Platform Engineer@Umeng
authorEmail: jinyuliang@umeng.com
authorNickname: gnailuy

# Frequently Used URL
url: http://gnailuy.com
urlAbout: /about

# Navigation Bar Items
navItems:
    - name: home
      url: /
    - name: posts
      url: /posts
    - name: about
      url: /about

# Image Tag
image:
    source: assets/images/_fullsize
    output: images
    presets:
        # Proportional preset
        fullWidth:
            width: 630
