# Site Information
name: gnailuy.com
markdown: redcarpet
pygments: true
permalink: pretty
url: http://gnailuy.com

# Author Information
author: Yuliang Jin
authorMsg: Data Platform Engineer@Umeng
authorEmail: jinyuliang@umeng.com
authorNickname: gnailuy

# Navigation Bar Items
navItems:
    - name: home
      path: /
    - name: about
      path: /about
